baseURL = 'https://example.org/'
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = 'UNIVILLE Competitive Programming'
theme = "hextra"


[menu]

  [[menu.main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 1

  [[menu.main]]
  name = "Reuniões"
  pageRef = "/reunioes"
  weight = 2

  [[menu.main]]
  name = "Editoriais"
  pageRef = "/editoriais"
  weight = 2

  [[menu.main]]
  name = "Sobre"
  pageRef = "/sobre"
  weight = 3

  [[menu.main]]
  name = "Procurar"
  weight = 4
    [menu.main.params]
    type = "search"

  [[menu.main]]
  name = "GitHub"
  weight = 5
  url = "https://github.com/univille-cp/"
      [menu.main.params]
      icon = "github"

enableGitInfo = true

[params]
displayUpdatedDate = true
dateFormat = "2 de January de 2006"
displayUpdatedAuthor = true


[params.search]
type = "flexsearch"
enable = true

[params.navbar.logo]
path = "images/logo.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params.footer]
displayPoweredBy = false

[services.googleAnalytics]
ID = "G-744NEFNQDQ"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
